using System.Threading.Tasks;

namespace MockInterview.API.Services
{
    public interface IAiAnalysisService
    {
        /// <summary>
        /// Analyzes the recorded interview video and provides feedback.
        /// </summary>
        /// <param name="videoPath">Path to the recorded video file.</param>
        /// <param name="resumeFilePath">Optional path to the user's resume for contextual analysis.</param>
        /// <param name="languageCode">Target language for analysis (e.g., hi-IN, kn-IN).</param>
        /// <returns>Feedback string generated by AI.</returns>
        Task<string> AnalyzeInterviewAsync(string videoPath, string? resumeFilePath = null, string languageCode = "en-IN");

        /// <summary>
        /// Generates interview questions based on the uploaded resume.
        /// </summary>
        /// <param name="resumeFilePath">Path to the resume file.</param>
        /// <param name="languageCode">Target language for questions.</param>
        /// <returns>JSON string containing a list of questions.</returns>
        Task<string> GenerateQuestionsFromResumeAsync(string resumeFilePath, string languageCode = "en-IN");
    }
}
